# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trunk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrunk.proto\x12\x1bsdv.edge.body.trunk.rear.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0bOpenRequest\x12\x0f\n\x07is_open\x18\x01 \x01(\x08\x32^\n\tRearTrunk\x12Q\n\rSetOpenStatus\x12(.sdv.edge.body.trunk.rear.v1.OpenRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trunk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPENREQUEST']._serialized_start=73
  _globals['_OPENREQUEST']._serialized_end=103
  _globals['_REARTRUNK']._serialized_start=105
  _globals['_REARTRUNK']._serialized_end=199
# @@protoc_insertion_point(module_scope)
